from __future__ import annotations

import os
import re
import hashlib
import hmac
import secrets
import time
from urllib.parse import urlsplit
from dataclasses import dataclass
from pathlib import Path
from typing import Any

SECRET_KEYS=re.compile(r"password|passwd|pwd|secret|token|api[_-]?key|private[_-]?key|credential",re.I)


def redact_secrets(value:Any)->Any:
    if isinstance(value,dict):
        return {k:("***" if SECRET_KEYS.search(str(k)) and v not in (None,"") else redact_secrets(v)) for k,v in value.items()}
    if isinstance(value,list): return [redact_secrets(v) for v in value]
    if isinstance(value,tuple): return tuple(redact_secrets(v) for v in value)
    return value


def safe_error_text(text:str,secrets:list[str|None]|None=None)->str:
    out=str(text)
    for secret in secrets or []:
        if secret: out=out.replace(secret,"***")
    out=re.sub(r"(?i)(password|token|api[_-]?key|secret)=([^\s;&]+)",r"\1=***",out)
    return out[:2000]


def safe_join(root:Path,name:str)->Path:
    root=root.resolve(); candidate=(root/name).resolve()
    if candidate!=root and root not in candidate.parents: raise ValueError("Path escapes configured workspace")
    return candidate


def max_upload_bytes()->int:
    return int(os.getenv("SYNTHETICFORGE_MAX_UPLOAD_BYTES",str(5*1024*1024)))


def production_mode() -> bool:
    return os.getenv("SYNTHETICFORGE_ENV", "development").strip().lower() == "production"


def validate_production_environment() -> None:
    """Fail startup closed instead of silently running a public dev server."""
    if not production_mode():
        return
    required = ["SYNTHETICFORGE_ADMIN_PASSWORD_HASH", "SYNTHETICFORGE_API_TOKEN_SHA256", "SYNTHETICFORGE_CORS_ORIGINS", "SYNTHETICFORGE_APPLICATION_SHA"]
    missing = [key for key in required if not os.getenv(key, "").strip()]
    if missing:
        raise RuntimeError("Production configuration missing: " + ", ".join(missing))
    api_hash = os.environ["SYNTHETICFORGE_API_TOKEN_SHA256"].strip()
    if not re.fullmatch(r"[0-9a-fA-F]{64}", api_hash):
        raise RuntimeError("SYNTHETICFORGE_API_TOKEN_SHA256 must be a SHA-256 hex digest")
    if not re.fullmatch(r"[0-9a-fA-F]{40,64}", os.environ["SYNTHETICFORGE_APPLICATION_SHA"].strip()):
        raise RuntimeError("SYNTHETICFORGE_APPLICATION_SHA must be the source commit SHA baked into the image")
    admin_hash = os.environ["SYNTHETICFORGE_ADMIN_PASSWORD_HASH"]
    try:
        scheme, rounds, salt, digest = admin_hash.split("$")
        if scheme != "pbkdf2_sha256" or int(rounds) < 600_000 or len(salt) < 22 or len(digest) < 40:
            raise ValueError
    except (ValueError, TypeError):
        raise RuntimeError("SYNTHETICFORGE_ADMIN_PASSWORD_HASH must be generated by scripts/hash_password.py") from None
    origins = [x.strip() for x in os.environ["SYNTHETICFORGE_CORS_ORIGINS"].split(",") if x.strip()]
    def valid_origin(origin:str)->bool:
        parsed=urlsplit(origin)
        return parsed.scheme=="https" and bool(parsed.hostname) and not parsed.username and not parsed.password and not parsed.path and not parsed.query and not parsed.fragment and "*" not in origin
    if not origins or any(not valid_origin(x) for x in origins):
        raise RuntimeError("Production CORS origins must be explicit HTTPS origins")
    if os.getenv("SYNTHETICFORGE_REPLICAS", "1").strip() != "1":
        raise RuntimeError("SQLite-backed production state supports exactly one application replica")
    if os.getenv("WEB_CONCURRENCY", "1").strip() != "1":
        raise RuntimeError("SQLite-backed production state supports exactly one application worker")
    try:
        if not 600<=int(os.getenv("SYNTHETICFORGE_SESSION_TTL_SECONDS","28800"))<=2_592_000:raise ValueError
        if not 1<=max_upload_bytes()<=100*1024*1024:raise ValueError
    except ValueError:raise RuntimeError("Session lifetime must be 600–2592000 seconds and max upload must be between 1 byte and 100 MiB") from None
    admin_api_hash=os.getenv("SYNTHETICFORGE_ADMIN_API_TOKEN_SHA256","").strip()
    if admin_api_hash and not re.fullmatch(r"[0-9a-fA-F]{64}",admin_api_hash):raise RuntimeError("SYNTHETICFORGE_ADMIN_API_TOKEN_SHA256 must be a SHA-256 hex digest")
    operator_user=os.getenv("SYNTHETICFORGE_OPERATOR_USERNAME","").strip()
    operator_hash=os.getenv("SYNTHETICFORGE_OPERATOR_PASSWORD_HASH","").strip()
    if bool(operator_user)!=bool(operator_hash):raise RuntimeError("Operator username and password hash must be configured together")
    if operator_hash:
        try:
            scheme, rounds, salt, digest=operator_hash.split("$")
            if scheme!="pbkdf2_sha256" or int(rounds)<600_000 or len(salt)<22 or len(digest)<40:raise ValueError
        except (ValueError,TypeError):raise RuntimeError("SYNTHETICFORGE_OPERATOR_PASSWORD_HASH must use the supported password hash format") from None


def hash_password(password: str, salt: bytes | None = None, rounds: int = 600_000) -> str:
    if len(password) < 14:
        raise ValueError("Password must contain at least 14 characters")
    salt = salt or secrets.token_bytes(18)
    digest = hashlib.pbkdf2_hmac("sha256", password.encode(), salt, rounds)
    import base64
    return f"pbkdf2_sha256${rounds}${base64.urlsafe_b64encode(salt).decode().rstrip('=')}${base64.urlsafe_b64encode(digest).decode().rstrip('=')}"


def verify_password(password: str, encoded: str) -> bool:
    import base64
    try:
        scheme, rounds, salt, expected = encoded.split("$")
        if scheme != "pbkdf2_sha256" or int(rounds) < 600_000:
            return False
        actual = hashlib.pbkdf2_hmac("sha256", password.encode(), base64.urlsafe_b64decode(salt + "=" * (-len(salt) % 4)), int(rounds))
        return hmac.compare_digest(actual, base64.urlsafe_b64decode(expected + "=" * (-len(expected) % 4)))
    except (ValueError, TypeError):
        return False


def token_hash(token: str) -> str:
    return hashlib.sha256(token.encode()).hexdigest()


def csrf_token(session_token: str) -> str:
    return hmac.new(session_token.encode(), b"syntheticforge-csrf-v1", hashlib.sha256).hexdigest()


@dataclass(frozen=True)
class AuthIdentity:
    username: str
    role: str
    session_id: str | None = None
    via: str = "session"
